name: CI

on:
  push:
  pull_request:

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - run: nix flake check --all-systems
      - run: ./tests.sh
